### ISSUE TITLE
[Enhancement] Add support to "F5"（Pseudocode window）

### ISSUE THREAD

**Issue by RandLily** [danigargu/deREferencing#20]
As a noob，I like using "F5" to debug , but I find this plugin is not synchronize with original ida stack and registers in "F5" ( Pseudocode window ) when step_into or step_over 。So I read the “dbg.py” and "IDADoc"，try to find a "srcdbg_step_over" and "srcdbg_step_into" hook to "reload_info"，but I failed。I really appreciate it if you can add this synchronous ability。

**Comment by rohitab** [comment]
I ran into the same issue where registers were not updating while single-stepping through the code. I was able to fix it by patching the file `dereferencing/dbg.py` with the following change:

**Original Code:**
https://github.com/danigargu/deREferencing/blob/2336d5ee82eba483bb1c3134c316639a35d625db/dereferencing/dbg.py#L77-L80

**Patched Code:**
```python
def dbg_suspend_process(self):
    if self.from_attach:
        self.from_attach = False
    self.notify()
```
As shown above, you need to move `self.notify()` outside the `if` statement.

**Comment by RandLily** [comment]
the best solution！！！thanks！！！

**Comment by danigargu** [comment]
Thanks! I'll update it when I have some time. I've also been adding code to display the arguments of the calls, based on the types defined in IDA.

**Comment by danigargu** [comment]
The problem with this patch is that `self.notify()` will be called twice (other callback and `dbg_suspend_process()`) and we lose information from the last updated registers. In the last tests I did, I saw that the best solution was to use only the `dbg_suspend_process()` callback, which directly calls `self.notify()`, and remove the rest (`dbg_step_into`, `dbg_step_over`, `dbg_step_into`...), but I need to do more tests, because I don't remember why I did it this way.

**Comment by rohitab** [comment]
You're absolutely right. I didn't notice it before, but while debugging in non-pseudocode view, the window does not show the last updated registers. To fix this and avoid duplicate calls, I removed the other functions that were calling `self.notify()`. The code seems to be working fine now. I've tested debugging in assembly, pseudocode and source code views.

If you remember why you decided to use the individual callbacks instead of `dbg_suspend_process`, please me know.

I've attached a patch with my changes, in case someone else wants to try it out.

Excellent plugin by the way!

[dereferencing-rohitab.patch.zip](https://github.com/danigargu/deREferencing/files/10149177/dereferencing-rohitab.patch.zip)

**Comment by Slluxx** [comment]
Will there be an official update anytime?
